### ISSUE TITLE
UTF-8 Encoding Arabic Support

### ISSUE THREAD

**Issue by AmrSubZero** [GideonLeGrange/mikrotik-java#40] opened 2016-07-07 04:56 UTC
As i know The API sends and receives the raw bytes

But when i try to display the arabic words correctly, it displays like "����" which seems to be "ISO-8859-1" or maybe "windows-1252" i don't know.

Is there an option allows me to change the API Charset Encoding to UTF-8? like the [Pear2/RouterOS](https://github.com/pear2/Net_RouterOS/wiki/Optional-features#automatic-charset-conversion) PHP API? (see the link).

or maybe convert the (diamond question marks) to "UTF-8" in Java? if so, please post an example!

I really need to correctly display arabic words, thanks.

**Comment by GideonLeGrange** [comment] 2016-07-09 11:48
Can you please provide me with an example RouterOS config so I can reproduce the problem?

**Comment by GideonLeGrange** [comment] 2016-07-11 14:21
@AmrSubZero  I'm looking into this. It should be possible to add a `setCharSet()` call that will allow you to get strings constructed with the right charset. I need to change code deep in the implementation which will cause some refactoring. I don't want to just patch and release code without being able to test, so I have two questions for you:

1. Can you please provide me with a sample Mikrotik configuration with Arabic characters in? 
2. Can you tell me what character encoding is the correct one? I'm thinking `cp1256` but is it?

Let me know please, I'd like to fix this.

**Comment by AmrSubZero** [comment] 2016-07-17 02:10
Sorry for being late, was in vacation.

First, i' have created a sample configuration working on **v5.25** of routerOS with arabic characters (comments column) for "_ip/hotspot/**users**_ & _**ip bindings**_" so you can connect, get and display the "**comment**" column for those, and test with them.

In the configuration the user is **admin** and there's no password
the **IN** or **WAN** Ethernet IP is 192.168.1.1 and the **OUT** or **LAN** or **LOCAL** IP is 10.0.0.1

I'm getting connected via **API** by connecting to **192.168.1.2** with the user **admin** and no password as i mentioned above, if there's a connection problem, please let me know.

[Here's the configuration file](https://mega.nz/#!CcwTRYQA!nmYNYNOm-LLU0yMWKCZtXxB2v73QkPnKjbvS5nkjHng)

Second, the correct charset is "**Windows-1256**".

I'm truly glad that you're ready to help, waiting you, thanks.

**Comment by AmrSubZero** [comment] 2016-10-08 08:54
Three months now and no progress!
i've searched the whole internet for a solution like [this one](stackoverflow.com/questions/39928496/android-convert-diamond-question-marks-to-utf-8-arabic-string) and found nothing.

please if you don't want to fix this, just tell me! i think this is an important feature to support multi character encoding to your API client, i paused my project for a long long time waiting you to tell me anything. please i need to display arabic in my app. Thanks Mr LeGrange.

**Comment by GideonLeGrange** [comment] 2016-10-08 15:38
When you complain, keep the following in mind:

You’re getting the software for free. You’re not a paying customer so getting pushy and demanding is going to be counter productive. 
This project isn’t my primary concern by a long shot. There are many, many other things in my life more important than this project, and it therefore receives attention if and when I have time to spend on it. 
You have the source code, you can try to figure the problem out for yourself and change the code and even submit 

Have you tried to figure out why this happens yourself?

**Comment by GideonLeGrange** [comment] 2016-10-08 17:09
@AmrSubZero I think I have a fix for this. If you want to test the fix, please pull the current master branch from github and build and try that version.

As an experiment, I've changed the internal encoding for transmission between the mikrotik-java API and RouterOS to be UTF-8 and it seems to solve the problem. I'll release version 3.0.3 shortly to make this change available.

Thanks to @boen_robot - your comments above pointed me in the right direction, which lead to this StackOverflow article http://stackoverflow.com/questions/5729806/encode-string-to-utf-8 

>A Java String is internally always encoded in UTF-16 - but you really should think about it like this: an encoding is a way to translate between Strings and bytes.
>So if you have an encoding problem, by the time you have String, it's too late to fix. You need to fix the place where you create that String from a file, DB or network connection.

**Comment by GideonLeGrange** [comment] 2016-10-08 18:40
@AmrSubZero 

This works for me. Can you please see if it works for you as well. 

**Example java code that creates users with Arabic, Japanese and Cyrillic text in comments**

```java
package examples;

import java.util.Map;
import me.legrange.mikrotik.MikrotikApiException;

/**
 * Example to show that different character sets may work some times. 
 *
 * @author gideon
 */
    
    private static final String JAPANESE = "事報ハヤ久送とゅ歳用ト候新放すルドう二5春園ユヲロ然納レ部悲と被状クヘ芸一ーあぽだ野健い産隊ず";
    private static final String CRYLLIC = "Лорем ипсум долор сит амет, легере елояуентиам хис ид. Елигенди нолуиссе вих ут. Нихил";
    private static final String ARABIC = "تجهيز والمانيا تم قام. وحتّى المتاخمة ما وقد. أسر أمدها تكبّد عل. فقد بسبب ترتيب استدعى أم, مما مع غرّة، لأداء. الشتاء، عسكرياً";

    private void test() throws MikrotikApiException {
        con.execute("/ip/hotspot/user/add name=userJ comment='" + JAPANESE + "'");
        con.execute("/ip/hotspot/user/add name=userC comment='" + CRYLLIC + "'");
        con.execute("/ip/hotspot/user/add name=userA comment='" + ARABIC + "'");

        for (Map<String, String> res : con.execute("/ip/hotspot/user/print return name,comment")) {
            System.out.printf("%s : %s\n", res.get("name"), res.get("comment"));
        }
    }
```

***Output from the that code***

```
default-trial : counters and limits for trial users
userJ : 事報ハヤ久送とゅ歳用ト候新放すルドう二5春園ユヲロ然納レ部悲と被状クヘ芸一ーあぽだ野健い産隊ず
userC : Лорем ипсум долор сит амет, легере елояуентиам хис ид. Елигенди нолуиссе вих ут. Нихил
userA : تجهيز والمانيا تم قام. وحتّى المتاخمة ما وقد. أسر أمدها تكبّد عل. فقد بسبب ترتيب استدعى أم, مما مع غرّة، لأداء. الشتاء، عسكرياً
```

***Screen shot of ssh login to Mikrotik***

![screen shot 2016-10-08 at 20 35 16](https://cloud.githubusercontent.com/assets/1131028/19215186/55e811ee-8d97-11e6-84c6-20e697f6d51e.png)

**Comment by AmrSubZero** [comment] 2016-10-09 05:58
I've updated the maven repo in my project to : `compile 'me.legrange:mikrotik:3.0.3'`

cleaned & rebuilt the project and tried the following examples :

`private static final String ARABIC = "تجربة نص عربى";`
`con.execute("/ip/hotspot/user/add name=userA comment='" + ARABIC + "'");`

Results : 

![usera](https://cloud.githubusercontent.com/assets/5399778/19218280/bdc2c45e-8df5-11e6-86e3-78eaa4b42cba.png)

and :

`for (Map<String, String> res : con.execute("/ip/hotspot/user/print return name,comment")) {
testArray.add(res.get("name") + " / " + res.get("comment"));`
`}`

Results :

![encoding](https://cloud.githubusercontent.com/assets/5399778/19218292/f5cd4554-8df5-11e6-9976-5743f4e05153.png)

My android xml file encoding is UTF-8 : 
`<?xml version="1.0" encoding="utf-8"?>`

What causes this problem?

**Comment by GideonLeGrange** [comment] 2016-10-09 17:28
On my setup the API and ssh command line show the same information, but Winbox and the web interface don't display them correctly, they look like in your pictures (I even enbled Arabic in my Chrome settings to see if the web interface will display correctly). 

So I have a question. If you ssh in to your mikrotik and do a ```/ip/hotspot/user print``` command, how are the users shown?

**Comment by GideonLeGrange** [comment] 2016-10-09 19:17
I've experimented some more and modified the API code to explicitly convert from cp1256 before sending data over the network and to convert to cp1256 when receiving data from the network (and before passing it to the user) and it makes no difference at all. I tried the same with iso-8859-6, no difference. 

The Arabic text set using the API looks correct from the router (ssh) command line, and it is read back correctly. But Winbox and the web interface do not show correctly. 

I suspect that Winbox and the web interface do not encode and decode the Arabic characters. I set Chrome's encoding settings (under View/Encoding) to "Arabic (Windows-1256) and it does not make any difference either. I tried with "Arabic (iso-8859-6)" as well, no difference. 

I fixed the encoding problem in the API in 3.0.3 and at this point the API will send non-English characters correctly and read them correctly. Other software is not working and I can't fix that. I think you're going to have to decide on a workaround for this problem. The options I see are:

- Trust Winbox and don't show the comments in your app. 
- Trust your app and ignore the fact that Winbox formats it badly. 
- Restrict your app and your users to English characters.

**Closed by GideonLeGrange** 2016-10-09 19:17 UTC
Labels: awaiting-feedback, not a bug

**Comment by AmrSubZero** [comment] 2016-10-10 00:33
I understand that you want to fix this, and i appreciate your help.

But let's discuss it.

As i asked ([this question](http://forum.mikrotik.com/viewtopic.php?f=9&t=109995)) **boen_robot** told me that **WinBox** displays the bytes using the **Windows ANSI charset** which is different for every locale.

And as i know, **boen_robot** is the owner of the **Pear2/RouterOS** PHP API for Mikrotik, he has a **Charset Configurable** that works correctly for each user configuration, as i mentioned in this **Issue** the [setCharset()](https://github.com/pear2/Net_RouterOS/wiki/Optional-features#automatic-charset-conversion) function, the user choosing the **REMOTE** and **LOCAL** charset, to Write to MikroTik with the correct charset, and Read from MikroTik also with the correct charset.

`//Here's where we specify the charset pair.`
`$client->setCharset(`
    `array(`
        `RouterOS\Communicator::CHARSET_REMOTE => 'windows-1256',`
        `RouterOS\Communicator::CHARSET_LOCAL  => 'UTF-8'`
   ` )`
`);`

The cool thing is that i tested his API using [setCharset()](https://github.com/pear2/Net_RouterOS/wiki/Optional-features#automatic-charset-conversion) and it works like a charm!

Writing to **MikroTik** from **API**, displayed the **Arabic** correctly in the **WinBox** : 

![winboxphp](https://cloud.githubusercontent.com/assets/5399778/19224929/2bd86828-8e90-11e6-9973-858f01b41065.png)

Reading from **MikroTik** through **API**, also displayed the **Arabic** correctly in the Web : 

![usersphp](https://cloud.githubusercontent.com/assets/5399778/19224932/43fb0dac-8e90-11e6-9dce-273eb158c5b0.png)

**boen_robot** [has recommended](http://forum.mikrotik.com/viewtopic.php?f=9&t=109995#p561898) you to create a **Charset Configurable** to fix this problem : 

![boen_robot](https://cloud.githubusercontent.com/assets/5399778/19224943/7168f420-8e90-11e6-9bad-2997360b216e.png)

Can that be achieved? is it possible to fix this by doing a **Charset Configurable** setCharset() method?

I'll be happy if that can be achieved, i have a huge data in my RouterOS the only way that i can distinction between each item and the other is the comment column and it will be too much easier to read it in arabic.

Let me know any step you take, please!

Thanks alot.

**Comment by GideonLeGrange** [comment] 2016-10-10 07:08
I tried manipulating the the charset and it does not solve it. Maybe I'm doing it wrong, but 
unfortunately I cannot spend more time on this. 

The library is open source and you can easily implement a ```setCharset()``` method yourself. If you do so and it fixes the problem, please submit a pull request for your changes.

**Comment by AmrSubZero** [comment] 2016-10-10 09:35
That is a bad news, but anyway, thanks Mr Gideon for your help.

**Comment by AbdelsalamHaa** [comment] 2018-05-02 08:54
Hi , I'm using tesseract 4 with vs 2017 . i have used with English characters first , now i started to include arabic as well . the thing is got weird characters even when i change the eng.traineddata to ara.traineddata. 

i found out that it's the characters when the UTF8 code is treated as Hex code . 
![image](https://user-images.githubusercontent.com/35866217/39512903-1cb50738-4e25-11e8-8d0b-eba47c163d8b.png)
 this is the image i want to recognize . 
the result is 
![image](https://user-images.githubusercontent.com/35866217/39513059-9a6a2424-4e25-11e8-9bcd-2eb56d3437b6.png)
i convert the letters in arabic to  UTF8 code using this website
https://r12a.github.io/app-conversion/
 and when i take this code and converted as a hex code to character i get the same characters that tesseract showed me the first time. 
"Ø¹Ø¨Ø¯Ø§Ù„Ø³Ù„Ø§Ù… Ù…Ø¯ÙŠ Ø¹Ø¨Ø¯Ø§Ù„Ø¹Ø²ÙŠØ²"

I think the problem is with UTF8 or might be my visual studio can't recognize Arabic letters or what

**Comment by GideonLeGrange** [comment] 2018-05-02 13:13
Hi 

You replied to a thread concerning the support for Arabic characters in an API used to program Mikrotik routers. I cannot help you with problems with Visual Studio. 

Gideon

**Comment by AbdelsalamHaa** [comment] 2018-05-03 01:05
@GideonLeGrange okay thanks for your reply

**Comment by mohamadtik** [comment] 2020-10-12 00:55
how i can used this code via class.php.api ????

//Here's where we specify the charset pair.
$client->setCharset(
array(
RouterOS\Communicator::CHARSET_REMOTE => 'windows-1256',
RouterOS\Communicator::CHARSET_LOCAL => 'UTF-8'
)
);

**Comment by GideonLeGrange** [comment] 2020-10-12 05:51
> how i can used this code via class.php.api ????
> 
> //Here's where we specify the charset pair.
> $client->setCharset(
> array(
> RouterOS\Communicator::CHARSET_REMOTE => 'windows-1256',
> RouterOS\Communicator::CHARSET_LOCAL => 'UTF-8'
> )
> );

I wrote and maintain a Java API. I cannot help you with a PHP API that somebody else wrote. Ask the author of that class.
